# Generated by Django 5.1.8 on 2025-04-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sitebrandingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebrandingsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
